#language
language: cpp

#compilers
compiler:
  - clang
  - gcc

os:
  - linux
  - osx

dist: trusty

sudo: true

addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-6
   - g++-6
   - build-essential
   - libgtk-3-dev
   - pkg-config

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - uname
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ln -sf /usr/bin/gcc-6 /usr/bin/gcc; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ln -sf /usr/bin/g++-6 /usr/bin/g++; fi
  - cd build && cmake .
  - cd build && make

install:
  - echo "No installation script!"
