#include <Aurora/TLib/Target/PragmaOnce.h>
#if defined(AURORA_TARGET_PRAGMA_ONCE_SUPPORT) && AURORA_TARGET_PRAGMA_ONCE_SUPPORT
    #pragma once
#endif

#include <Aurora/Common.h>

#ifndef INCLUDE_H_AURORA_GENGINE_INPUT
#define INCLUDE_H_AURORA_GENGINE_INPUT

#include <Aurora/GEngine/Window.h>

//Max Array Values
#define AURORA_GENGINE_INPUT_MAX_KEYS    1024
#define AURORA_GENGINE_INPUT_MAX_BUTTONS 32

///Keycodes
//Mouse
#define AURORA_GENGINE_MOUSE_LEFT
#define AURORA_GENGINE_MOUSE_MIDDLE
#define AURORA_GENGINE_MOUSE_RIGHT

#define AURORA_GENGINE_KEY_ESC
#define AURORA_GENGINE_KEY_SHIFT
#define AURORA_GENGINE_KEY_TAB
#define AURORA_GENGINE_KEY_CTRL
#define AURORA_GENGINE_KEY_ALT
#define AURORA_GENGINE_KEY_SUPER
#define AURORA_GENGINE_KEY_SPACE
#define AURORA_GENGINE_KEY_UP
#define AURORA_GENGINE_KEY_DOWN
#define AURORA_GENGINE_KEY_LEFT
#define AURORA_GENGINE_KEY_RIGHT

#define AURORA_GENGINE_KEY_INSERT
#define AURORA_GENGINE_KEY_DELETE
#define AURORA_GENGINE_KEY_END
#define AURORA_GENGINE_KEY_HOME
#define AURORA_GENGINE_KEY_PAGEUP
#define AURORA_GENGINE_KEY_PAGEDOWN

//Numbers
#define AURORA_GENGINE_KEY_0
#define AURORA_GENGINE_KEY_1
#define AURORA_GENGINE_KEY_2
#define AURORA_GENGINE_KEY_3
#define AURORA_GENGINE_KEY_4
#define AURORA_GENGINE_KEY_5
#define AURORA_GENGINE_KEY_6
#define AURORA_GENGINE_KEY_7
#define AURORA_GENGINE_KEY_8
#define AURORA_GENGINE_KEY_9

//Letters
#define AURORA_GENGINE_KEY_A
#define AURORA_GENGINE_KEY_B
#define AURORA_GENGINE_KEY_C
#define AURORA_GENGINE_KEY_D
#define AURORA_GENGINE_KEY_E
#define AURORA_GENGINE_KEY_F
#define AURORA_GENGINE_KEY_G
#define AURORA_GENGINE_KEY_H
#define AURORA_GENGINE_KEY_I
#define AURORA_GENGINE_KEY_J
#define AURORA_GENGINE_KEY_K
#define AURORA_GENGINE_KEY_L
#define AURORA_GENGINE_KEY_M
#define AURORA_GENGINE_KEY_N
#define AURORA_GENGINE_KEY_O
#define AURORA_GENGINE_KEY_P
#define AURORA_GENGINE_KEY_Q
#define AURORA_GENGINE_KEY_R
#define AURORA_GENGINE_KEY_S
#define AURORA_GENGINE_KEY_T
#define AURORA_GENGINE_KEY_U
#define AURORA_GENGINE_KEY_V
#define AURORA_GENGINE_KEY_W
#define AURORA_GENGINE_KEY_X
#define AURORA_GENGINE_KEY_Y
#define AURORA_GENGINE_KEY_Z

//Function Keys
#define AURORA_GENGINE_KEY_F1
#define AURORA_GENGINE_KEY_F2
#define AURORA_GENGINE_KEY_F3
#define AURORA_GENGINE_KEY_F4
#define AURORA_GENGINE_KEY_F5
#define AURORA_GENGINE_KEY_F6
#define AURORA_GENGINE_KEY_F7
#define AURORA_GENGINE_KEY_F8
#define AURORA_GENGINE_KEY_F9
#define AURORA_GENGINE_KEY_F10
#define AURORA_GENGINE_KEY_F11
#define AURORA_GENGINE_KEY_F12

//Numpad
#define AURORA_GENGINE_KEY_NUMLOCK
#define AURORA_GENGINE_KEY_NUMPAD0
#define AURORA_GENGINE_KEY_NUMPAD1
#define AURORA_GENGINE_KEY_NUMPAD2
#define AURORA_GENGINE_KEY_NUMPAD3
#define AURORA_GENGINE_KEY_NUMPAD4
#define AURORA_GENGINE_KEY_NUMPAD5
#define AURORA_GENGINE_KEY_NUMPAD6
#define AURORA_GENGINE_KEY_NUMPAD7
#define AURORA_GENGINE_KEY_NUMPAD8
#define AURORA_GENGINE_KEY_NUMPAD9

namespace Aurora {
    namespace GEngine {
        class Input {
            Input(Window* );
            ~Input();
        public:
            bool isKeyPressed(unsigned int keycode) const;
            bool isButtonPressed(unsigned int button) const;
            void getMousePosition(double& x, double& y) const;
        private:
            bool keys[AURORA_GENGINE_INPUT_MAX_KEYS];
            bool buttons[AURORA_GENGINE_INPUT_MAX_BUTTONS];
            double mx, my;
        };
    }
}

#endif // INCLUDE_H_AURORA_GENGINE_INPUT
